# Generated by Django 4.0 on 2022-01-04 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Cost_per_item', models.DecimalField(decimal_places=20, max_digits=20)),
                ('Stock_quantity', models.DecimalField(decimal_places=20, max_digits=20)),
                ('Volume', models.BigIntegerField(null=True)),
            ],
        ),
    ]
